version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: snap-hutao-generic-api:1.0
    container_name: Snap-Hutao-Generic-API
    ports:
      - "3975:8080"
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - tunnel
      - scheduled-tasks

  redis:
    container_name: Snap-Hutao-Generic-API-Redis
    image: redis:latest
    volumes:
      - ./redis:/data
    restart: unless-stopped

  scheduled-tasks:
    build:
      context: .
      dockerfile: Dockerfile-scheduled-tasks
      target: runtime
    image: scheduled_tasks
    container_name: Snap-Hutao-Generic-API-Scheduled-Tasks
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
    depends_on:
      - redis

  tunnel:
    container_name: Snap-Hutao-Generic-API-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=snap-hutao-generic-api-tunnel-token
