version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: ${IMAGE_NAME}-server:latest
    container_name: ${IMAGE_NAME}-server
    ports:
      - "${EXTERNAL_PORT}:8080"
    networks:
      - snaphutao_network
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - scheduled-tasks
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: ${IMAGE_NAME}-redis
    image: redis:latest
    volumes:
      - /data/docker-service/redis_cache/${IMAGE_NAME}:/data
    networks:
      - snaphutao_network
    restart: unless-stopped

  scheduled-tasks:
    build:
      context: .
      dockerfile: Dockerfile-scheduled-tasks
      target: runtime
    image: scheduled_tasks
    networks:
      - snaphutao_network
    container_name: ${IMAGE_NAME}-scheduled-tasks
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tunnel:
    container_name: ${IMAGE_NAME}-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - snaphutao_network

networks:
  snaphutao_network:
    external: true