#!/bin/sh
# Build Stage
FROM python:3.12 AS builder
WORKDIR /code
ADD . /code
RUN pip install --no-cache-dir -r /code/scheduled-tasks-requirements.txt
RUN pyinstaller -F scheduled_tasks.py

# Runtime
FROM ubuntu:22.04 AS runtime
ENV TZ="Asia/Shanghai"
WORKDIR /app
COPY --from=builder /code/dist/scheduled_tasks .
EXPOSE 8080
ENTRYPOINT ["./scheduled_tasks"]