version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: ${IMAGE_NAME}-server:latest
    container_name: ${IMAGE_NAME}-server
    ports:
      - "3975:8080"
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - tunnel
      - scheduled-tasks

  redis:
    container_name: ${IMAGE_NAME}-redis
    image: redis:latest
    volumes:
      - ./redis:/data
    restart: unless-stopped

  scheduled-tasks:
    build:
      context: .
      dockerfile: Dockerfile-scheduled-tasks
      target: runtime
    image: scheduled_tasks
    container_name: ${IMAGE_NAME}-scheduled-tasks
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
    depends_on:
      - redis
